version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - db_backend
    environment:
      API_PREFIX: /api
      API_PORT: 3000
      MYSQL_HOST: mysql_service
      MYSQL_PORT: 3307
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: todo_db
    container_name: api_server

  mysql_service:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - '3307:3306'
    networks:
      - db_backend
    container_name: api_db

volumes:
  db_data:
networks:
  db_backend:
